const GAME_DATA = [
    { text: "おはようございます", display: "おはようございます", romaji: "ohayougozaimasu", imageKeyword: "morning" },
    { text: "いただきます", display: "いただきます", romaji: "itadakimasu", imageKeyword: "eating" },
    { text: "いってきます", display: "いってきます", romaji: "ittekimasu", imageKeyword: "leaving" },
    { text: "ただいま", display: "ただいま", romaji: "tadaima", imageKeyword: "home" },
    { text: "おやすみなさい", display: "おやすみなさい", romaji: "oyasuminasai", imageKeyword: "sleeping" },
    { text: "ありがとう", display: "ありがとう", romaji: "arigatou", imageKeyword: "thankyou" },
    { text: "ごめんなさい", display: "ごめんなさい", romaji: "gomennasai", imageKeyword: "sorry" },
    { text: "がっこうへいく", display: "がっこうへいく", romaji: "gakkouheiku", imageKeyword: "school" },
    { text: "ほんをよむ", display: "ほんをよむ", romaji: "honwoyomu", imageKeyword: "reading" },
    { text: "ともだちとあそぶ", display: "ともだちとあそぶ", romaji: "tomodatitoasobu", imageKeyword: "playing" },
    { text: "きゅうしょくをたべる", display: "きゅうしょくをたべる", romaji: "kyuushokuwotaberu", imageKeyword: "eating" },
    { text: "しゅくだいをする", display: "しゅくだいをする", romaji: "shukudaiwosuru", imageKeyword: "studying" },
    { text: "てをあらう", display: "てをあらう", romaji: "tewoarau", imageKeyword: "washing" },
    { text: "はをみがく", display: "はをみがく", romaji: "hawomigaku", imageKeyword: "brushing" },
    { text: "おふろにはいる", display: "おふろにはいる", romaji: "ofuronihairu", imageKeyword: "bath" },
    { text: "いぬのさんぽ", display: "いぬのさんぽ", romaji: "inunosanpo", imageKeyword: "walking_dog" },
    { text: "ねこがねている", display: "ねこがねている", romaji: "nekoganeteiru", imageKeyword: "cat_sleeping" },
    { text: "さっかーをする", display: "さっかーをする", romaji: "sakka-wosuru", imageKeyword: "soccer" },
    { text: "ぴあのをひく", display: "ぴあのをひく", romaji: "pianowohiku", imageKeyword: "piano" },
    { text: "えをかく", display: "えをかく", romaji: "ewokaku", imageKeyword: "drawing" },
    { text: "うたをうたう", display: "うたをうたう", romaji: "utawoutau", imageKeyword: "singing" },
    { text: "げーむをする", display: "げーむをする", romaji: "ge-muwosuru", imageKeyword: "gaming" },
    { text: "おやつをたべる", display: "おやつをたべる", romaji: "oyatuwotaberu", imageKeyword: "snack" },
    { text: "てれびをみる", display: "てれびをみる", romaji: "terebiwo miru", imageKeyword: "tv" },
    { text: "じてんしゃにのる", display: "じてんしゃにのる", romaji: "jitensyaninoru", imageKeyword: "cycling" },
    { text: "すいとうをもつ", display: "すいとうをもつ", romaji: "suitouwomotu", imageKeyword: "waterbottle" },
    { text: "ぼうしをかぶる", display: "ぼうしをかぶる", romaji: "bousiwokaburu", imageKeyword: "hat" },
    { text: "くつをはく", display: "くつをはく", romaji: "kut uwohaku", imageKeyword: "shoes" },
    { text: "あしたははれ", display: "あしたははれ", romaji: "asitawahare", imageKeyword: "sunny" },
    { text: "げんきにあいさつ", display: "げんきにあいさつ", romaji: "genkiniaisatu", imageKeyword: "greeting" },

    // Study (Grade 1-2)
    { text: "こくごのほんをよむ", display: "こくごのほんをよむ", romaji: "kokugonohonwo yomu", imageKeyword: "study_japanese" },
    { text: "さんすうのどりる", display: "さんすうのどりる", romaji: "sansuunodoriru", imageKeyword: "study_math" },
    { text: "かんじのれんしゅう", display: "かんじのれんしゅう", romaji: "kanjinorenshu", imageKeyword: "study_kanji" },
    { text: "えんぴつをもつ", display: "えんぴつをもつ", romaji: "enpituwomotu", imageKeyword: "pencil" },
    { text: "せんせいとはなす", display: "せんせいとはなす", romaji: "senseitohanasu", imageKeyword: "teacher" },

    // Travel
    { text: "ひこうきにのる", display: "ひこうきにのる", romaji: "hikoukininoru", imageKeyword: "airplane" },
    { text: "でんしゃでいこう", display: "でんしゃでいこう", romaji: "denshadeikou", imageKeyword: "train" },
    { text: "うみへいく", display: "うみへいく", romaji: "umiheiku", imageKeyword: "sea" },
    { text: "おんせんにはいる", display: "おんせんにはいる", romaji: "onsennihairu", imageKeyword: "hotspring" },
    { text: "おみやげをかう", display: "おみやげをかう", romaji: "omiyagewokau", imageKeyword: "souvenir" }
];
